/**
 * api-worker/src/index.ts
 *
 * Main Cloudflare Worker entry point.
 *
 * Responsibilities:
 *  1. Handle CORS preflight (OPTIONS) requests.
 *  2. Route /ws/tenant/:tenantId WebSocket upgrades → TenantOrderDO.
 *  3. Route /trpc/* HTTP requests → tRPC fetchRequestHandler.
 *  4. Return 404 for everything else.
 *
 * How Cloudflare Workers work:
 *  - There is no Express/Koa. Instead you export a `fetch` handler.
 *  - `env` contains all bindings (D1, KV, Durable Objects, secrets).
 *  - `ctx` contains `waitUntil` for background tasks.
 */

import { fetchRequestHandler } from '@trpc/server/adapters/fetch';
import { appRouter } from './trpc/routers/_app';
import { createContext } from './trpc/context';

// Re-export the Durable Object class so Wrangler can register it.
// This MUST be a named export matching the class_name in wrangler.toml.
export { TenantOrderDO } from './dos/TenantOrderDO';

// ── Environment bindings type ──────────────────────────────────────────────
// Auto-generated by `pnpm cf-typegen` – kept here for clarity.
export interface Env {
  /** Cloudflare D1 SQLite database. */
  DB: D1Database;
  /** Durable Object namespace for real-time order broadcasting. */
  TENANT_ORDER_DO: DurableObjectNamespace;
  /** Comma-separated allowed CORS origins. */
  CORS_ORIGIN: string;
  ENVIRONMENT: string;
}

// ── CORS helper ────────────────────────────────────────────────────────────

function corsHeaders(origin: string, allowedOrigins: string): HeadersInit {
  // Only reflect the origin back if it is in the allow-list.
  const allowed = allowedOrigins.split(',').map((o) => o.trim());
  const reflect = allowed.includes(origin) ? origin : allowed[0] ?? '*';
  return {
    'Access-Control-Allow-Origin':  reflect,
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Access-Control-Max-Age':       '86400',
  };
}

// ── Worker fetch handler ───────────────────────────────────────────────────

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url    = new URL(request.url);
    const origin = request.headers.get('origin') ?? '';
    const cors   = corsHeaders(origin, env.CORS_ORIGIN ?? '*');

    // ── CORS preflight ─────────────────────────────────────────────
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: cors });
    }

    // ── WebSocket upgrade: /ws/tenant/:tenantId ────────────────────
    // The client sends an Upgrade: websocket header.
    // We forward the request to the TenantOrderDO responsible for this tenant.
    if (url.pathname.startsWith('/ws/tenant/')) {
      const upgradeHeader = request.headers.get('Upgrade');
      if (!upgradeHeader || upgradeHeader.toLowerCase() !== 'websocket') {
        return new Response('Expected WebSocket upgrade', { status: 426 });
      }

      // Extract tenantId from the path
      const tenantId = url.pathname.split('/ws/tenant/')[1];
      if (!tenantId) {
        return new Response('Missing tenantId', { status: 400 });
      }

      // Each tenant maps to a SINGLE Durable Object instance.
      // Using idFromName(tenantId) ensures the same DO handles all
      // connections for a given tenant – enabling group broadcasts.
      const doId   = env.TENANT_ORDER_DO.idFromName(tenantId);
      const doStub = env.TENANT_ORDER_DO.get(doId);

      // Forward the full request (including WS headers) to the DO.
      return doStub.fetch(request);
    }

    // ── tRPC handler: /trpc/* ──────────────────────────────────────
    if (url.pathname.startsWith('/trpc')) {
      const response = await fetchRequestHandler({
        endpoint: '/trpc',
        req:      request,
        router:   appRouter,
        // Pass DB + DO bindings through tRPC context
        createContext: () => createContext({ req: request, env, ctx }),
      });

      // Attach CORS headers to every tRPC response
      const headers = new Headers(response.headers);
      for (const [key, value] of Object.entries(cors)) {
        headers.set(key, value);
      }
      return new Response(response.body, { status: response.status, headers });
    }

    // ── 404 ────────────────────────────────────────────────────────
    return new Response(
      JSON.stringify({ error: 'Not found', path: url.pathname }),
      { status: 404, headers: { 'Content-Type': 'application/json', ...cors } }
    );
  },
} satisfies ExportedHandler<Env>;
