// Generated by Wrangler by running `wrangler types --env-interface Env`

interface Env {
	ENVIRONMENT: "development" | "production";
	CORS_ORIGIN: "http://localhost:3000,http://localhost:3001" | "https://nummygo-customer-web.alaminshaheen23.workers.dev,https://nummygo-tenant-web.alaminshaheen23.workers.dev";
	CUSTOMER_WEB_URL: "http://localhost:3000" | "https://nummygo-customer-web.alaminshaheen23.workers.dev";
	TENANT_WEB_URL: "http://localhost:3001" | "https://nummygo-tenant-web.alaminshaheen23.workers.dev";
	BETTER_AUTH_URL: "http://localhost:8787" | "https://nummygo-api.alaminshaheen23.workers.dev";
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
}
